using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EShopping.Utilities
{
    public static class MimeUtilities
    {
        public static string GetByExtension(string ext)
        {
            return mimeContentTypes.ContainsKey(ext) ? mimeContentTypes[ext] : string.Empty;
        }

        private static Dictionary<string, string> mimeContentTypes = new Dictionary<string, string>()
        {
            { "aac", "audio/aac" },
            { "abw", "application/x-abiword" },
            { "arc", "application/x-freearc" },
            { "avi", "video/x-msvideo" },
            { "azw", "application/vnd.amazon.ebook" },
            { "bin", "application/octet-stream" },
            { "bmp", "image/bmp" },
            { "bz", "application/x-bzip" },
            { "bz2", "application/x-bzip2" },
            { "csh", "application/x-csh" },
            { "css", "text/css" },
            { "csv", "text/csv" },
            { "doc", "application/msword" },
            { "docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
            { "eot", "application/vnd.ms-fontobject" },
            { "epub", "application/epub+zip" },
            { "gif", "image/gif" },
            { "htm", "text/html" },
            { "html", "text/html" },
            { "ico", "image/vnd.microsoft.icon" },
            { "ics", "text/calendar" },
            { "jar", "application/java-archive" },
            { "jpeg", "image/jpeg" },
            { "jpg", "image/jpeg" },
            { "js", "text/javascript" },
            { "json", "application/json" },
            { "mid", "audio/midi audio/x-midi" },
            { "midi", "audio/midi audio/x-midi" },
            { "mjs", "application/javascript" },
            { "mp3", "audio/mpeg" },
            { "mpeg", "video/mpeg" },
            { "mpkg", "application/vnd.apple.installer+xml" },
            { "odp", "application/vnd.oasis.opendocument.presentation" },
            { "ods", "application/vnd.oasis.opendocument.spreadsheet" },
            { "odt", "application/vnd.oasis.opendocument.text" },
            { "oga", "audio/ogg" },
            { "ogv", "video/ogg" },
            { "ogx", "application/ogg" },
            { "otf", "font/otf" },
            { "png", "image/png" },
            { "pdf", "application/pdf" },
            { "ppt", "application/vnd.ms-powerpoint" },
            { "pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation" },
            { "rar", "application/x-rar-compressed" },
            { "sh", "application/x-sh" },
            { "svg", "image/svg+xml" },
            { "swf", "application/x-shockwave-flash" },
            { "tar", "application/x-tar" },
            { "tif", "image/tiff" },
            { "tiff", "image/tiff" },
            { "ttf", "font/ttf" },
            { "txt", "text/plain" },
            { "vsd", "application/vnd.visio" },
            { "wav", "audio/wav" },
            { "weba", "audio/webm" },
            { "webm", "video/webm" },
            { "webp", "image/webp" },
            { "woff", "font/woff" },
            { "woff2", "font/woff2" },
            { "xhtml", "application/xhtml+xml" },
            { "xls", "application/vnd.ms-excel" },
            { "xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
            { "xml", "application/xml" },
            { "xul", "application/vnd.mozilla.xul+xml" },
            { "zip", "application/zip" },
            { "3gp", "video/3gpp" },
            { "3g2", "video/3gpp2" },
            { "x3d", "application/vnd.hzn-3d-crossword" },
            { "7z", "application/x-7z-compressed" },
            { "mseq", "application/vnd.mseq" },
            { "pwn", "application/vnd.3m.post-it-notes" },
            { "plb", "application/vnd.3gpp.pic-bw-large" },
            { "psb", "application/vnd.3gpp.pic-bw-small" },
            { "pvb", "application/vnd.3gpp.pic-bw-var" },
            { "tcap", "application/vnd.3gpp2.tcap" },
            { "ace", "application/x-ace-compressed" },
            { "acc", "application/vnd.americandynamics.acc" },
            { "acu", "application/vnd.acucobol" },
            { "atc", "application/vnd.acucorp" },
            { "adp", "audio/adpcm" },
            { "aab", "application/x-authorware-bin" },
            { "aam", "application/x-authorware-map" },
            { "aas", "application/x-authorware-seg" },
            { "air", "application/vnd.adobe.air-application-installer-package+zip" },
            { "fxp", "application/vnd.adobe.fxp" },
            { "ppd", "application/vnd.cups-ppd" },
            { "dir", "application/x-director" },
            { "xdp", "application/vnd.adobe.xdp+xml" },
            { "xfdf", "application/vnd.adobe.xfdf" },
            { "ahead", "application/vnd.ahead.space" },
            { "azf", "application/vnd.airzip.filesecure.azf" },
            { "azs", "application/vnd.airzip.filesecure.azs" },
            { "ami", "application/vnd.amiga.ami" },
            { "N/A", "application/andrew-inset" },
            { "apk", "application/vnd.android.package-archive" },
            { "cii", "application/vnd.anser-web-certificate-issue-initiation" },
            { "fti", "application/vnd.anser-web-funds-transfer-initiation" },
            { "atx", "application/vnd.antix.game-component" },
            { "dmg", "application/x-apple-diskimage" },
            { "aw", "application/applixware" },
            { "les", "application/vnd.hhe.lesson-player" },
            { "swi", "application/vnd.aristanetworks.swi" },
            { "s", "text/x-asm" },
            { "atomcat", "application/atomcat+xml" },
            { "atomsvc", "application/atomsvc+xml" },
            { "atom", "application/atom+xml" },
            { "ac", "application/pkix-attr-cert" },
            { "aif", "audio/x-aiff" },
            { "aep", "application/vnd.audiograph" },
            { "dxf", "image/vnd.dxf" },
            { "dwf", "model/vnd.dwf" },
            { "par", "text/plain-bas" },
            { "bcpio", "application/x-bcpio" },
            { "torrent", "application/x-bittorrent" },
            { "cod", "application/vnd.rim.cod" },
            { "mpm", "application/vnd.blueice.multipass" },
            { "bmi", "application/vnd.bmi" },
            { "btif", "image/prs.btif" },
            { "rep", "application/vnd.businessobjects" },
            { "c", "text/x-c" },
            { "cdxml", "application/vnd.chemdraw+xml" },
            { "cdx", "chemical/x-cdx" },
            { "cml", "chemical/x-cml" },
            { "csml", "chemical/x-csml" },
            { "cdbcmsg", "application/vnd.contact.cmsg" },
            { "cla", "application/vnd.claymore" },
            { "c4g", "application/vnd.clonk.c4group" },
            { "sub", "image/vnd.dvb.subtitle" },
            { "cdmia", "application/cdmi-capability" },
            { "cdmic", "application/cdmi-container" },
            { "cdmid", "application/cdmi-domain" },
            { "cdmio", "application/cdmi-object" },
            { "cdmiq", "application/cdmi-queue" },
            { "c11amc", "application/vnd.cluetrust.cartomobile-config" },
            { "c11amz", "application/vnd.cluetrust.cartomobile-config-pkg" },
            { "ras", "image/x-cmu-raster" },
            { "dae", "model/vnd.collada+xml" },
            { "cpt", "application/mac-compactpro" },
            { "wmlc", "application/vnd.wap.wmlc" },
            { "cgm", "image/cgm" },
            { "ice", "x-conference/x-cooltalk" },
            { "cmx", "image/x-cmx" },
            { "xar", "application/vnd.xara" },
            { "cmc", "application/vnd.cosmocaller" },
            { "cpio", "application/x-cpio" },
            { "clkx", "application/vnd.crick.clicker" },
            { "clkk", "application/vnd.crick.clicker.keyboard" },
            { "clkp", "application/vnd.crick.clicker.palette" },
            { "clkt", "application/vnd.crick.clicker.template" },
            { "clkw", "application/vnd.crick.clicker.wordbank" },
            { "wbs", "application/vnd.criticaltools.wbs+xml" },
            { "cryptonote", "application/vnd.rig.cryptonote" },
            { "cif", "chemical/x-cif" },
            { "cmdf", "chemical/x-cmdf" },
            { "cu", "application/cu-seeme" },
            { "cww", "application/prs.cww" },
            { "curl", "text/vnd.curl" },
            { "dcurl", "text/vnd.curl.dcurl" },
            { "mcurl", "text/vnd.curl.mcurl" },
            { "scurl", "text/vnd.curl.scurl" },
            { "car", "application/vnd.curl.car" },
            { "pcurl", "application/vnd.curl.pcurl" },
            { "cmp", "application/vnd.yellowriver-custom-menu" },
            { "dssc", "application/dssc+der" },
            { "xdssc", "application/dssc+xml" },
            { "deb", "application/x-debian-package" },
            { "uva", "audio/vnd.dece.audio" },
            { "uvi", "image/vnd.dece.graphic" },
            { "uvh", "video/vnd.dece.hd" },
            { "uvm", "video/vnd.dece.mobile" },
            { "uvu", "video/vnd.uvvu.mp4" },
            { "uvp", "video/vnd.dece.pd" },
            { "uvs", "video/vnd.dece.sd" },
            { "uvv", "video/vnd.dece.video" },
            { "dvi", "application/x-dvi" },
            { "seed", "application/vnd.fdsn.seed" },
            { "dtb", "application/x-dtbook+xml" },
            { "res", "application/x-dtbresource+xml" },
            { "ait", "application/vnd.dvb.ait" },
            { "svc", "application/vnd.dvb.service" },
            { "eol", "audio/vnd.digital-winds" },
            { "djvu", "image/vnd.djvu" },
            { "dtd", "application/xml-dtd" },
            { "mlp", "application/vnd.dolby.mlp" },
            { "wad", "application/x-doom" },
            { "dpg", "application/vnd.dpgraph" },
            { "dra", "audio/vnd.dra" },
            { "dfac", "application/vnd.dreamfactory" },
            { "dts", "audio/vnd.dts" },
            { "dtshd", "audio/vnd.dts.hd" },
            { "dwg", "image/vnd.dwg" },
            { "geo", "application/vnd.dynageo" },
            { "es", "application/ecmascript" },
            { "mag", "application/vnd.ecowin.chart" },
            { "mmr", "image/vnd.fujixerox.edmics-mmr" },
            { "rlc", "image/vnd.fujixerox.edmics-rlc" },
            { "exi", "application/exi" },
            { "mgz", "application/vnd.proteus.magazine" },
            { "eml", "message/rfc822" },
            { "nml", "application/vnd.enliven" },
            { "xpr", "application/vnd.is-xpr" },
            { "xif", "image/vnd.xiff" },
            { "xfdl", "application/vnd.xfdl" },
            { "emma", "application/emma+xml" }
        };


    }
}
